db:
  user: Alexandr Kamelchukov
  username: postgres
  password: password
  url: jdbc:postgresql://localhost:5432/postgres
  poolSize: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
logging:
  level:
    root: WARN
    ru.lexkml.spring.database: INFO

