db:
  user: Alexandr Kamelchukov
  username: postgres
  password: password
  url: jdbc:postgresql://localhost:5432/postgres
  poolSize: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
logging:
  level:
    root: info
  file:
    name: lexkml.log
    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

